[project]
name = "nixos"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "typer>=0.27.2",
]

[project.scripts]
rig = "rig.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
dev-mode-dirs = [
    ".",
    "core/pkgs",
]
