color0 #12333f
color1 #fd4663
color2 #67d8e4
color3 #5c8cd6
color4 #837bee
color5 #93e3ec
color6 #96b6e9
color7 #f2f3f3
color8 #616f70
color9 #fd4663
color10 #67d8e4
color11 #5c8cd6
color12 #837bee
color13 #93e3ec
color14 #96b6e9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #0e2630
background            #0e2630
foreground            #f2f3f3
selection_foreground  #afb6b6
selection_background  #12333f
active_border_color   #67d8e4
inactive_border_color #12333f
url_color             #67d8e4

active_tab_foreground   #182325
active_tab_background   #67d8e4
inactive_tab_foreground #afb6b6
inactive_tab_background #12333f
cursor_trail_color      #afb6b6
